//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahwa.Attila.UI.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int MvxSpinnerTemplate = 2130771970;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int add_category = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int add_market = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int add_product = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int add_shoppingitem = 2130968596;
			
			// aapt resource value: 0x7f040008
			public const int change_category = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int change_market = 2130968589;
			
			// aapt resource value: 0x7f040011
			public const int change_product = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int change_shoppingitem = 2130968597;
			
			// aapt resource value: 0x7f040009
			public const int delete_category = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int delete_market = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int delete_product = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int delete_shoppingitem = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int list_category = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int list_market = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int list_product = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int list_shoppingitem = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int save_category = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int save_market = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int save_product = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int save_shoppingitem = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int txtShoppingItemName = 2130968578;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoryDetailsView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryEditView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CategoryListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CategoryListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MarketDetailsView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MarketEditView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MarketListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MarketListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProductDetailsView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ProductEditView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ProductListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ProductListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ShoppingItemDetailsView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ShoppingItemEditView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ShoppingItemListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ShoppingItemListView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SplashScreen = 2130903056;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int category_add_menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int category_edit_menu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int category_list_menu = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int category_menu = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int market_add_menu = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int market_edit_menu = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int market_list_menu = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int market_menu = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int product_add_menu = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int product_edit_menu = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int product_list_menu = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int product_menu = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int shoppingitem_add_menu = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int shoppingitem_edit_menu = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int shoppingitem_list_menu = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int shoppingitem_menu = 2131099663;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Loading = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int label_category_name = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int label_get_coordinates = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int label_market_latitude = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int label_market_longitude = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int label_market_name = 2131034120;
			
			// aapt resource value: 0x7f05001a
			public const int label_product_barcodebutton = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int label_product_barcodevalue = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int label_product_browsepicturebutton = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int label_product_category = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int label_product_name = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int label_product_takepicturebutton = 2131034140;
			
			// aapt resource value: 0x7f050024
			public const int label_shoppingitem_category = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int label_shoppingitem_name = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int label_shoppingitem_quantity = 2131034149;
			
			// aapt resource value: 0x7f05000b
			public const int label_show_on_map = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int menu_add_category = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int menu_add_market = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int menu_add_product = 2131034131;
			
			// aapt resource value: 0x7f05001e
			public const int menu_add_shoppingitem = 2131034142;
			
			// aapt resource value: 0x7f05000f
			public const int menu_change_category = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int menu_change_market = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int menu_change_product = 2131034133;
			
			// aapt resource value: 0x7f050020
			public const int menu_change_shoppingitem = 2131034144;
			
			// aapt resource value: 0x7f050010
			public const int menu_delete_category = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int menu_delete_market = 2131034118;
			
			// aapt resource value: 0x7f050016
			public const int menu_delete_product = 2131034134;
			
			// aapt resource value: 0x7f050021
			public const int menu_delete_shoppingitem = 2131034145;
			
			// aapt resource value: 0x7f050011
			public const int menu_list_category = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int menu_list_market = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int menu_list_product = 2131034135;
			
			// aapt resource value: 0x7f050022
			public const int menu_list_shoppingitem = 2131034146;
			
			// aapt resource value: 0x7f05000e
			public const int menu_save_category = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int menu_save_market = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int menu_save_product = 2131034132;
			
			// aapt resource value: 0x7f05001f
			public const int menu_save_shoppingitem = 2131034143;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBindableSpinner = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxBindableSpinner_MvxSpinnerTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			private Styleable()
			{
			}
		}
	}
}
